[package]
name = "hotel-scheduling-puzzle"
version = "0.1.0"
authors = ["Arnaud Gourlay <arnaud.gourlay@commercetools.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
